name: TheraBot Test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'

            - name: Install packages
              run: npm install

            - name: Run tests
              run: npm test
